=== ismagambetov/XmlParser/src/main/resources/dance.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.epam.com/ism/danceProgramms"
    xmlns="http://www.epam.com/ism/danceProgramms">

    <xsd:element name="dance">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="danceRoutine" type="DanceRoutine" minOccurs="1" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>

    </xsd:element>

    <xsd:complexType name="DanceRoutine">
        <xsd:sequence>
            <xsd:element name = "type" type = "xsd:string"/>
            <xsd:element name = "scene" type = "xsd:string"/>
            <xsd:element name ="musicAccompaniment" type = "Music" />
            <xsd:element name ="dancers" type = "Dancers" />
        </xsd:sequence>
        <xsd:attribute name = "orderInProgram" type = "xsd:ID" use = "required" />
        <xsd:attribute name = "actName" type = "xsd:string" use = "optional" />
        <xsd:attribute name = "typeOfCollective" use = "required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="mass"/>
                    <xsd:enumeration value="pair"/>
                    <xsd:enumeration value="solo"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="Music">
        <xsd:sequence>
            <xsd:element name = "genre">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Hip-Hop"/>
                        <xsd:enumeration value="Ballad"/>
                        <xsd:enumeration value="Reggaeton"/>
                        <xsd:enumeration value="Rock"/>
                        <xsd:enumeration value="Dubstep"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name = "title" type="xsd:string"/>
            <xsd:element name = "duration" type="xsd:float"/>
        </xsd:sequence>


        <xsd:attribute name ="type" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="phonogram" />
                    <xsd:enumeration value="live music" />
                </xsd:restriction>
            </xsd:simpleType>

        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="Dancers">
        <xsd:sequence>
            <xsd:element name = "dancer" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type = "xsd:string"/>
                        <xsd:element name="age" type = "xsd:integer"/>
                        <xsd:element name="experience" type = "xsd:integer"/>
                    </xsd:sequence>
                </xsd:complexType>

            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="groupName" type="xsd:string" />
        <xsd:attribute name="numberOfMembers" type="xsd:integer" />
    </xsd:complexType>
</xsd:schema>

=== ismagambetov/XmlParser/src/main/resources/dance.xml
<?xml version ="1.0" encoding = "UTF-8"?>
<d:dance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.epam.com/ism/danceProgramms dance.xsd"
         xmlns:d="http://www.epam.com/ism/danceProgramms">
        <danceRoutine orderInProgram = "id1" actName = "title1" typeOfCollective = "mass">
            <type>break-dance</type>
            <scene>street</scene>
            <musicAccompaniment type = "phonogram">
                <genre>Hip-Hop</genre>
                <title>Please stand up</title>
                <duration>4.25</duration>
            </musicAccompaniment>
            <dancers groupName = "Quest Crew" numberOfMembers = "5">
                <dancer>
                    <name>Hokuto Konishi</name>
                    <age>17</age>
                    <experience>2</experience>
                </dancer>

                <dancer>
                    <name>Steve Terada</name>
                    <age>19</age>
                    <experience>3</experience>
                </dancer>

                <dancer>
                    <name>Ryan Conferido</name>
                    <age>18</age>
                    <experience>3</experience>
                </dancer>

                <dancer>
                    <name>Dominic Sandoval</name>
                    <age>20</age>
                    <experience>3</experience>
                </dancer>

                <dancer>
                    <name>Aris Paracuelles</name>
                    <age>19</age>
                    <experience>3</experience>
                </dancer>

            </dancers>
        </danceRoutine>

        <danceRoutine orderInProgram = "id2" actName = "title2" typeOfCollective = "pair">
            <type>Viennese waltz</type>
            <scene>Palace Belvedere</scene>
            <musicAccompaniment type = "phonogram">
                <genre>Ballad</genre>
                <title>Hijo de la Luna</title>
                <duration>4.14</duration>
            </musicAccompaniment>
            <dancers groupName = "The Angels" numberOfMembers = "2">
                <dancer>
                    <name>Brian Williams</name>
                    <age>25</age>
                    <experience>10</experience>
                </dancer>

                <dancer>
                    <name>Nancy Hill</name>
                    <age>23</age>
                    <experience>9</experience>
                </dancer>

            </dancers>
        </danceRoutine>

        <danceRoutine orderInProgram = "id3" actName = "title3" typeOfCollective = "solo">
            <type>Latina Solo</type>
            <scene>Assembly hall</scene>
            <musicAccompaniment type = "phonogram">
                <genre>Reggaeton</genre>
                <title>Ayudame Imaginar</title>
                <duration>3.51</duration>
            </musicAccompaniment>
            <dancers groupName = "" numberOfMembers = "1">
                <dancer>
                    <name>Katherine Ramirez</name>
                    <age>25</age>
                    <experience>15</experience>
                </dancer>
            </dancers>
        </danceRoutine>
</d:dance>
